global:
  resolve_timeout: 2m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email_notification'
receivers:
  - name: 'email_notification'
    email_configs:
      #  - url: 'http://127.0.0.1:5001/'
      - to: divya.ynt@gmail.com
        from: divya.ynt@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: divya.ynt@gmail.com
        auth_identity: divya.ynt@gmail.com
        auth_password: 
        send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
