name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Prometheus
        run: |
          wget https://github.com/prometheus/prometheus/releases/download/v0.3.0/prometheus-0.3.0.linux-amd64.tar.gz
          tar xvfz prometheus-0.3.0.linux-amd64.tar.gz
          sudo mv prometheus-0.3.0.linux-amd64/promtool /usr/local/bin/
          rm -rf prometheus-0.3.0.linux-amd64.tar.gz prometheus-0.3.0.linux-amd64/

      - name: Build and Deploy Prometheus Configuration
        run: |
          # Copy Prometheus configuration files
          cp prometheus.yml /etc/prometheus/prometheus.yml
          cp alert.rules.yml /etc/prometheus/alert.rules.yml

          # Reload Prometheus
          systemctl reload prometheus

      - name: Build and Deploy Alertmanager Configuration
        run: |
          # Copy Alertmanager configuration file
          cp alertmanager.yml /etc/alertmanager/alertmanager.yml

          # Reload Alertmanager
          systemctl reload alertmanager
