name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  llinting_and_testing:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        wget https://github.com/prometheus/prometheus/releases/download/v0.3.0/prometheus-0.3.0.linux-amd64.tar.gz
        tar xvfz prometheus-0.3.0.linux-amd64.tar.gz
        sudo mv prometheus-0.3.0.linux-amd64/promtool /usr/local/bin/
        rm -rf prometheus-0.3.0.linux-amd64.tar.gz prometheus-2.30.3.linux-amd64/

    - name: Linting
      run: |
        # Run linting checks
        promtool check config prometheus.yml
        promtool check rules alert.rules.yml

    - name: Testing
      run: |
        ./test.sh


  building_and_deploying:
    runs-on: ubuntu-latest
    needs: linting_and_testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: # Add commands to build and deploy your Prometheus configuration
